### ISSUE TITLE
Undefined command error

### ISSUE THREAD

**Issue by wilmer-suarez** [pgosar/ChatGDB#5]
Any way around this? I'm running `arm-none-eabi-gdb`

```
.../.gdbinit:1: Error in sourced command file:
/opt/homebrew/lib/python3.11/site-packages/chatgdb/core.py:3: Error in sourced command file:
Undefined command: "from".
```

**Comment by pgosar** [comment]
I think what happened is that the response to your input was an undefined command in GDB?

Generally, this issue happens when the GPT model hallucinates commands, which happens occasionally (in my testing, it's quite rare). There is unfortunately no way of stopping that from happening.

**Comment by wilmer-suarez** [comment]
This happens during GDBs initialization actually, before inputting any command:
![Screenshot 2023-04-09 at 1 09 34 PM](https://user-images.githubusercontent.com/88936793/230786588-7dc11975-70f9-49f0-9dfb-d5b9bfeb550b.png)

This is what's in my `.gdbinit` file:
![Screenshot 2023-04-09 at 1 12 10 PM](https://user-images.githubusercontent.com/88936793/230786632-52fcedf1-d19b-4f0b-9026-465ca85a7642.png)

**Comment by pgosar** [comment]
After doing some research, I think the issue may have something to do with your ```arm-none-eabi-gdb``` not being compiled with python support. There should not be an issue with the script.

**Comment by wilmer-suarez** [comment]
Yeah, that seems to be the case. If I can figure out a way to get past that I will post here. Thank you

**Comment by pgosar** [comment]
I came across this, you might find it helpful. 
https://gist.github.com/JayKickliter/8004bafaf3d365dc8fe23843fae15c67

Let me know if it works.
