### ISSUE TITLE
Please cite ChatDBG, which precedes this work (and does more)

### ISSUE THREAD

**Issue by emeryberger** [pgosar/ChatGDB#6]
See https://github.com/plasma-umass/chatdbg. It precedes your work by several weeks (at least) and also strictly does more, including root cause analysis and proposing fixes. Thanks (ChatDBG author).

**Comment by pgosar** [comment]
Hey @emeryberger -- thanks for sharing your project, we hadn't seen it before! We built this project during a hackathon as a group of undergraduate TAs for the Operating Systems course here at UT Austin based on what we noticed students in the course were struggling with (I see we share this alma mater -- go longhorns!). This isn't an academic work and we just wanted to build a tool that people find helpful, so we don't believe a literature review is applicable or needed. Let us know if you disagree with this!

If you can share some examples of how other open source projects (non-academic works) cite related projects that would give some guidance on best practices here, that would be helpful! We don't usually see many open source projects cite related works regardless of when they were created and it's common that different people independently have similar ideas that they pursue.

Thank you!

**Comment by ardasahiner** [comment]
Drive-by comment here, just asking for clarification.

Is it common to cite other open-source projects when creating one of your own, especially when the two projects don't depend on each other? Not really something I've seen before, and just curious if there are examples of this?

Regardless, have enjoyed the projects and excited to see where they go!

**Comment by emeryberger** [comment]
I'm going to quote a wise man and fellow Longhorn here: "[...] if someone told me that (they) had done it first and better I would surely add a link to their work."
