### ISSUE TITLE
Good first steps for contributing?

### ISSUE THREAD

**Issue by iitjee** [pgosar/ChatGDB#7]
Hi developers,
Can you point me to good first steps towards learning the pre-reqs for this project (video tutorials, books etc). I was always passionate about the idea of a smoother debugging workflow, but hardly have any idea as to how to 'hack into' a code-editor's debugger and make it work programmatically. Any help is much appreciated. Looking forward to making a small contribution to this amazing project! 😁 Thank you!

**Comment by pgosar** [comment]
The first step would be to take a look at the [contribution guidelines](https://github.com/pgosar/ChatGDB/blob/main/CONTRIBUTING.md). When writing this project, this [blog post](https://fy.blackhats.net.au/blog/html/2017/08/04/so_you_want_to_script_gdb_with_python.html) was my first step - the existing code is a good template to learn how I made the custom commands.
